script_template: inno_setup.iss
app_id: 2DD55137-C734-446E-B1DC-3FCB5445025D
app_name: FlClash Plus
publisher_name: AI68
publisher_url: https://mingjie-panel.ai68ai.cn
display_name: FlClash Plus
executable_name: FlClashPlus.exe
output_base_file_name: FlClashPlus-Setup.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin
